### ISSUE TITLE
Some apps not respecting my theme. 

### ISSUE THREAD

**Issue by TechNerd-019** [EliverLara/Nordic#221]
Fedora Workstation 36 with GNOME 42

GTK version 3.24.34

I installed the Nordic Dark v40 theme and it did not apply to all apps. Some GNOME apps, like calculator, Text Editor, and Software Center did not get the change.
I downloaded the archive and installed it to the .themes folder and ran the following commands:
gsettings set org.gnome.desktop.interface gtk-theme Nordic-darker-v40
gsettings set org.gnome.desktop.wm.preferences theme Nordic-darker-v40

Screenshot demonstrating the issue is provided. The latest version of the theme was downloaded from [here](https://www.gnome-look.org/p/1267246/).

![image](https://user-images.githubusercontent.com/91811442/178161459-3886946d-ca87-4062-a389-2d40ca7da581.png)

**Comment by EliverLara** [comment]
> https://github.com/odziom91/libadwaita-theme-changer
> 
> try this
> 
> this may not help with everything, but most should be fine

this should fix the issue

**Comment by Demetrio92** [comment]
@EliverLara getting Nordic-v40 directly from gnome look. 

> https://github.com/odziom91/libadwaita-theme-changer

Still does not fix Nautilus. 


![Screenshot from 2022-12-04 00-20-10](https://user-images.githubusercontent.com/22682408/205467817-fa8db084-6ada-4d98-b70c-2dbe5b4d09e3.png)

**Comment by Demetrio92** [comment]
the only recourse I had for nautilus: 

```
sudo apt install nemo
xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
```

_curses in libadwaita_
